### ISSUE TITLE
dato-icon-button deafult size is wrong

### ISSUE THREAD

**Issue by shaharkazaz** [datorama/client-core#11]
According to the docs the default size is "md"
Without datSize property set:
![image](https://user-images.githubusercontent.com/17194830/40045449-fe2bf0a2-5832-11e8-944d-14a2e8b70d72.png)
With datoSize set to "md":
![image](https://user-images.githubusercontent.com/17194830/40045501-278774ee-5833-11e8-8fc2-f8c24c869ec3.png)

**Comment by NetanelBasal** [comment]
done
