### ISSUE TITLE
Tooltip - when the text is too long - the tooltip is displayed in an offset and attaches to another component

### ISSUE THREAD

**Issue by TicaTac** [datorama/client-core#110]
This is the Correct behavior - Tooltip appears at the Bottom of the component

This is the Bug - when the text is too long - the tooltip appears under another component with a wrong indication of source - seems related to the component at the side of the real one.

**Comment by NetanelBasal** [comment]
This is not a bug. You should refactor your CSS. Check the width of the element that the tooltip is on.
