### ISSUE TITLE
dato-slider | step option not working properly, inputs not updated

### ISSUE THREAD

**Issue by ninamor** [datorama/client-core#143]
1. in the following example, the value of the slider does not comply with the step.
range: [0, 8], step: 0.08
![image](https://user-images.githubusercontent.com/38883723/49578351-395f9500-f952-11e8-9730-6e254394146a.png)
2. in the same example, changing the min input to 3 does not effect the slider:
![image](https://user-images.githubusercontent.com/38883723/49578452-76c42280-f952-11e8-9eed-89fd686315c9.png)

**Comment by YonathanMeguira** [comment]
when working with small values (<1), slider does not update the inputs. change filter event on update (must also accept values < 1)
