### ISSUE TITLE
dato-slider | multi cursor - moving one cursor makes the other one move es well

### ISSUE THREAD

**Issue by ninamor** [datorama/client-core#156]
when moving one cursor too close to the other, the one we didn't touch moves unexpectedly.

**Comment by YonathanMeguira** [comment]
@ninamor ok, I will take a look at it, it's by design that we allow grabbing the cursor within a 6px radius around the cursors.
So when too close, it also gets inside the radius of the second cursor. Will fix this

**Comment by YonathanMeguira** [comment]
fixed, in PR: https://github.com/datorama/client-core/pull/160
