### ISSUE TITLE
Dato select single selection change background color

### ISSUE THREAD

**Issue by ofirb25** [datorama/client-core#174]
the selected item in the dropdown of a signle selection component should have accent-400 as background color.

```dato-select__option dato-select__option--simple dato-select__option--hover dato-option--active```

![screen shot 2019-01-08 at 16 08 38](https://user-images.githubusercontent.com/29405083/50835574-b8842680-135f-11e9-84a2-cb613f6a1e82.png)

**Comment by NetanelBasal** [comment]
It's a mistake; it should be as is.
