### ISSUE TITLE
dato-checkbox click area issue

### ISSUE THREAD

**Issue by ritox842** [datorama/client-core#20]
I'm using the dato-checkbox in my edit field form. 
The input click area is overlapping other form elements and in general not in it's proper positioning.

![image](https://user-images.githubusercontent.com/7280441/40297401-6783c872-5ce8-11e8-9284-b5ba90e018ef.png)
 
The image above show's the input positioning for the first checkbox ('Show on axis').

I'm using the latest core version (1.0.54-beta).

**Comment by NetanelBasal** [comment]
It's not a problem with the core, check the core example and compare the styles to yours.
