### ISSUE TITLE
Popover initial placement is not correct

### ISSUE THREAD

**Issue by YonathanMeguira** [datorama/client-core#209]
**URGENT: Needed for current sprint (1.6.8)**

**issue**: When opening the Popover, at first it does not get the specified placement, it only gets it after scrolling.

**reproducing**: open a popover with `{placement: 'top-end'}`. 
**expected behavior**: should open up on top-end
**actual result**: opens up  on the right side , will be at top-end only after scroll on the page.

_Note: No other events will update the popover position except scrolling on the page._

**Comment by NetanelBasal** [comment]
remove the screenshot, please.
